databases:
  # Configuração MySQL com SSL
  - name: "mysql_producao"
    type: "mysql"
    host: "mysql-prod.exemplo.com"
    port: 3306
    database: "production"
    username: "monitor_user"
    password: "senha_segura_mysql"
    ssl_mode: "REQUIRED"
    cert_path: "certs/mysql_producao"
    connect_timeout: 30
    query_timeout: 30

  # Configuração MySQL sem SSL (para desenvolvimento)
  - name: "mysql_desenvolvimento"
    type: "mysql"
    host: "localhost"
    port: 3306
    database: "dev"
    username: "root"
    password: "root123"
    ssl_mode: "DISABLED"
    cert_path: ""
    connect_timeout: 10
    query_timeout: 15

  # Configuração PostgreSQL com SSL
  - name: "postgres_producao"
    type: "postgresql"
    host: "postgres-prod.exemplo.com"
    port: 5432
    database: "production"
    username: "monitor_user"
    password: "senha_segura_postgres"
    ssl_mode: "require"
    cert_path: "certs/postgres_producao"
    connect_timeout: 30
    query_timeout: 30

  # Configuração PostgreSQL sem SSL
  - name: "postgres_desenvolvimento"
    type: "postgresql"
    host: "localhost"
    port: 5432
    database: "dev"
    username: "postgres"
    password: "postgres123"
    ssl_mode: "disable"
    cert_path: ""
    connect_timeout: 10
    query_timeout: 15

  # Configuração PostgreSQL com SSL verify-full
  - name: "postgres_critico"
    type: "postgresql"
    host: "postgres-critical.exemplo.com"
    port: 5432
    database: "critical"
    username: "monitor_user"
    password: "senha_muito_segura"
    ssl_mode: "verify-full"
    cert_path: "certs/postgres_critico"
    connect_timeout: 30
    query_timeout: 45

# Configuração de email
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "monitor@exemplo.com"
  password: "senha_aplicacao_gmail"  # Use App Password para Gmail
  from_email: "monitor@exemplo.com"
  to_emails:
    - "admin@exemplo.com"
    - "dba@exemplo.com"
    - "suporte@exemplo.com"
  use_tls: true

# Configuração de notificação via Slack
slack:
  webhook_url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"

# Configuração de thresholds para alertas
thresholds:
  active_connections: 80      # Alerta se conexões ativas > 80
  inactive_connections: 100   # Alerta se conexões inativas > 100
  total_connections: 150      # Alerta se total de conexões > 150

# Configuração do pool de conexões e monitoramento
pool:
  max_open_conns: 5
  max_idle_conns: 2
  conn_max_lifetime: 3600    # Em segundos (1 hora)
  conn_max_idle_time: 600    # Em segundos (10 minutos)
  health_check_interval: 30  # Em segundos
  backoff_initial: 1         # Em segundos
  backoff_max: 60            # Em segundos

# Configuração geral da aplicação
application:
  monitoring_interval: 60        # Intervalo de monitoramento em segundos
  health_check_interval: 300     # Intervalo de verificação de saúde do pool em segundos
  alert_reset_interval: 3600     # Intervalo para resetar contadores de alerta em segundos
  alert_frequency: 10            # Frequência de envio de alertas (ex: a cada 10 ocorrências)
  http_server_address: ":8080"   # Endereço para o servidor HTTP